import os
from dotenv import load_dotenv

load_dotenv()

BOT_TOKEN = os.getenv("BOT_TOKEN", "YOUR_BOT_TOKEN_HERE")
ADMIN_IDS_STR = os.getenv("ADMIN_IDS", "123456789,65440516,8540875314")
ADMIN_IDS = [int(x.strip()) for x in ADMIN_IDS_STR.split(",") if x.strip().isdigit()]

SHOP_TO_ORG = {
    "Писта": "Zafarxon",
    "Курт А": "Zafarxon",
    "Курт Б": "Zafarxon",
    "Курт Ж": "Ermak plus",
    "Сок Ж": "Ermak plus",
    "Сушка С": "Zafarxon",
    "Бодом": "Zafarxon",
    "Казинаки Ф": "Ermak Alo",
    "Охонгарн": "Zafarxon plus",
    "Tennis": "Tennis"
}

ORG_CARDS = {
    "Zafarxon": ["5614 6814 3026 3925", "5614 6814 3086 6321"],
    "Ermak plus": ["5614 6814 3012 0687", "5614 6814 3034 7413", "5614 6814 3046 7583"],
    "Ermak Alo": ["5614 6814 3020 9993", "5614 6814 3077 3220"],
    "Zafarxon plus": ["5614 6814 3069 2719", "5614 6814 3048 2178"],
    "Теннис": ["5614 6814 3065 2374"]
}

UNITS = ["кг", "шт", "метр", "литр", "см"]

MESSAGES = {
    "ru": {
        "choose_lang": "Выберите язык:",
        "enter_performer": "Введите Исполнителя (Фамилия и первая буква имени, например: Иванов И.):",
        "choose_shop": "Выберите цех:",
        "choose_payment": "Выберите карту или НАЛ:",
        "choose_unit": "Выберите единицу измерения:",
        "enter_price": "Введите цену:",
        "enter_qty": "Введите количество:",
        "enter_nom": "Введите номенклатуру (Наименование товара):",
        "enter_tmc": "Введите группу ТМЦ:",
        "enter_supplier": "Введите поставщика:",
        "success": "✅ Данные успешно сохранены!",
        "error": "❌ Произошла ошибка при сохранении. Обратитесь к разработчику.",
        "no_rights": "У вас нет прав для выполнения этой команды.",
        "file_not_found": "Файл еще не создан или произошла ошибка.",
        "invalid_number": "Пожалуйста, введите корректное число:",
        "invalid_shop": "Пожалуйста, выберите цех с помощью клавиатуры.",
        "new_record_btn": "📝 Новая запись",
        "receipt_btn": "📷 Отправить чек",
        "main_menu": "Главное меню. Нажмите «📝 Новая запись» на клавиатуре для начала.",
        "confirm_msg": "Проверьте данные:\n\nЦех: {shop}\nОплата: {payment}\nЕд. изм.: {unit}\nЦена: {price}\nКоличество: {quantity}\nСумма: {total}\nНоменклатура: {nomenclature}\nТМЦ: {tmc_group}\nПоставщик: {supplier}\n\nВсё ли верно?",
        "confirm_performer": "Вы ввели: {performer}.\n⚠️ Внимание: вы НЕ сможете изменить это имя в будущем!\nПодтверждаете?",
        "performer_saved": "Имя Исполнителя успешно сохранено!",
        "success": "✅ Данные успешно сохранены в таблицу!",
        "error": "❌ Ошибка при сохранении данных.",
        "cancelled": "❌ Ввод отменен.",
        "yes": "Да",
        "no": "Нет",
        "reading_receipt": "⏳ Читаю чек, подождите...",
        "ai_recognized": "📄 <b>Распознано с чека:</b>\n",
        "ai_date": "📅 Дата: <b>{val}</b>",
        "ai_payment": "💳 Оплата: <b>{val}</b>",
        "ai_payment_card": " (карта **** {val})",
        "ai_nom": "🏷 Наименование: <b>{val}</b>",
        "ai_price": "💰 Цена: <b>{val}</b>",
        "ai_qty": "📦 Количество: <b>{val}</b>",
        "ai_supplier": "🏪 Поставщик: <b>{val}</b>",
        "ai_confirm_prompt": "Данные верные?",
        "ai_partial_fail": "⚠️ Заполните недостающие данные вручную:",
        "ai_fail": "❌ Ошибка чтения. Заполните вручную.",
        "ai_yes_success": "✅ Выберите цех:",
        "ai_no_manual": "✏️ Заполните вручную:",
        "ai_hint": " ({val})",
        "only_photo": "📷 Пожалуйста, отправьте именно фото чека.",
        "press_yes_no": "Нажмите Да или Нет.",
        "cancel_btn": "Отмена",
        "cash_btn": "НАЛ",
        "finish_btn": "Закончить чек",
        "next_btn": "Далее",
        "enter_note": "Введите примечание (или нажмите Далее, если нет):",
        "add_more_prompt": "🛒 Добавить еще один товар с этого чека?",
        "ai_items_header": "🛒 <b>Товары ({val} шт):</b>",
        "ai_item_calc": "     💰 {price} × {qty} шт = <b>{total}</b>",
        "current_item_header": "\n🛍 <b>Товар {i} из {total}:</b> {nom}\n",
        "current_item_manual": "\n🛍 <b>Добавление товара:</b>\n",
        "reg_required": "Регистрация обязательна.",
        "choose_lang_menu": "Выберите язык из меню.\nMenyudan tilni tanlang.",
        "send_receipt_prompt": "📷 Отправьте фото чека. Если чек большой — отправьте несколько фото по частям, затем нажмите Готово.",
        "send_qr_prompt": "📷 Отправьте фото QR-кода с чека или просто скопируйте и отправьте ссылку (начинается с https://new-ofd.soliq.uz/...):",
        "photo_accepted": "✅ Фото {n} принято. Отправьте ещё или нажмите Готово.",
        "reading_receipt_multi": "⏳ Читаю чек ({n} фото), подождите...",
        "done_btn": "Готово",
        "ai_date_not_found": "📅 Дата: <b>не найдена</b>",
        "ai_no_items": "⚠️ Товары не найдены",
        "final_check_header": "<b>Проверьте данные чека:</b>\n",
        "final_shop": "Цех: {val}",
        "final_payment": "Оплата: {val}",
        "final_supplier": "Поставщик: {val}\n",
        "final_items_header": "<b>Товары ({val} шт):</b>",
        "final_item_line": "{i}. {nom} — {qty} шт x {price} = {total}",
        "final_receipt_tmc_note": "\n<b>ТМЦ:</b> {tmc}\n<b>Примечание:</b> {note}",
        "final_total": "\n<b>ИТОГО:</b> {val}",
        "final_ask": "\nВсё ли верно?",
        "qr_not_found": "❌ На фото не найден QR-код с ссылкой на soliq.uz. Пожалуйста, отправьте отдельное фото QR-кода с чека.",
        "qr_found": "✅ Найдена ссылка на чек: {link}",
        "edit_menu_title": "Выберите, что хотите изменить:",
        "edit_supplier_btn": "🏢 Поставщик",
        "edit_item_btn": "🛍 {nom}",
        "edit_done_btn": "✅ Готово",
        "edit_full_manual_btn": "✏️ Ввести полностью вручную",
        "edit_item_title": "Что изменить в товаре «{nom}»?",
        "edit_name_btn": "🏷 Название",
        "edit_price_btn": "💰 Цена",
        "edit_qty_btn": "📦 Количество",
        "edit_back_btn": "🔙 Назад",
        "enter_new_supplier": "Введите нового поставщика:",
        "enter_new_name": "Введите новое название:",
        "enter_new_price": "Введите новую цену:",
        "enter_new_qty": "Введите новое количество:",
        "edit_saved": "✅ Изменения успешно сохранены!",
        "edit_grand_total_btn": "💰 Общая сумма",
        "enter_new_grand_total": "Введите новую общую сумму:"
    },
    "uz": {
        "choose_lang": "Tilni tanlang:",
        "enter_performer": "Ijrochini kiriting (Familiyasi va ismining birinchi harfi, masalan: Ivanov I.):",
        "choose_shop": "Sexni tanlang:",
        "choose_payment": "Karta yoki NAKHD ni tanlang:",
        "choose_unit": "O'lchov birligini tanlang:",
        "enter_price": "Narxni kiriting:",
        "enter_qty": "Miqdorni kiriting:",
        "enter_nom": "Nomenklaturani (Mahsulot nomini) kiriting:",
        "enter_tmc": "TMC guruhini kiriting:",
        "enter_supplier": "Yetkazib beruvchini kiriting:",
        "no_rights": "Ushbu buyruqni bajarish uchun sizda huquq yo'q.",
        "file_not_found": "Fayl hali yaratilmagan yoki xatolik yuz berdi.",
        "invalid_number": "Iltimos, to'g'ri raqam kiriting:",
        "invalid_shop": "Iltimos, klaviatura orqali sexni tanlang.",
        "new_record_btn": "📝 Yangi yozuv",
        "receipt_btn": "📷 Chek yuborish",
        "main_menu": "Asosiy menyu. Boshlash uchun pastdagi «📝 Yangi yozuv» tugmasini bosing.",
        "confirm_msg": "Ma'lumotlarni tekshiring:\n\nSex: {shop}\nTo'lov: {payment}\nO'lchov: {unit}\nNarx: {price}\nMiqdor: {quantity}\nSumma: {total}\nNomenklatura: {nomenclature}\nTMC: {tmc_group}\nYetkazib beruvchi: {supplier}\n\nBarchasi to'g'rimi?",
        "confirm_performer": "Siz kiritdingiz: {performer}.\n⚠️ Diqqat: bu ismni kelajakda o'zgartira olmaysiz!\nTasdiqlaysizmi?",
        "performer_saved": "Bajaruvchi ismi muvaffaqiyatli saqlandi!",
        "success": "✅ Ma'lumotlar jadvalga muvaffaqiyatli saqlandi!",
        "error": "❌ Ma'lumotlarni saqlashda xatolik yuz berdi.",
        "cancelled": "❌ Kiritish bekor qilindi.",
        "yes": "Ha",
        "no": "Yo'q",
        "reading_receipt": "⏳ Chek o'qilmoqda, kuting...",
        "ai_recognized": "📄 <b>Chekdan o'qildi:</b>\n",
        "ai_date": "📅 Sana: <b>{val}</b>",
        "ai_payment": "💳 To'lov: <b>{val}</b>",
        "ai_payment_card": " (karta **** {val})",
        "ai_nom": "🏷 Nomi: <b>{val}</b>",
        "ai_price": "💰 Narx: <b>{val}</b>",
        "ai_qty": "📦 Miqdor: <b>{val}</b>",
        "ai_supplier": "🏪 Yetkazib beruvchi: <b>{val}</b>",
        "ai_confirm_prompt": "Ma'lumotlar to'g'rimi?",
        "ai_partial_fail": "⚠️ Yetishmayotgan ma'lumotlarni qo'lda kiriting:",
        "ai_fail": "❌ O'qishda xatolik. Qo'lda kiriting.",
        "ai_yes_success": "✅ Sexni tanlang:",
        "ai_no_manual": "✏️ Qo'lda kiriting:",
        "ai_hint": " ({val})",
        "only_photo": "📷 Iltimos, faqat chek rasmini yuboring.",
        "press_yes_no": "Ha yoki Yo'q tugmasini bosing.",
        "cancel_btn": "Bekor qilish",
        "cash_btn": "NAKHD",
        "finish_btn": "Chekni tugatish",
        "next_btn": "Keyingisi",
        "enter_note": "Izoh kiriting (yoki yo'q bo'lsa Keyingisini bosing):",
        "add_more_prompt": "🛒 Ushbu chekdan yana bitta mahsulot qo'shasizmi?",
        "ai_items_header": "🛒 <b>Mahsulotlar ({val} ta):</b>",
        "ai_item_calc": "     💰 {price} × {qty} dona = <b>{total}</b>",
        "current_item_header": "\n🛍 <b>{total} tadan {i}-mahsulot:</b> {nom}\n",
        "current_item_manual": "\n🛍 <b>Mahsulot qo'shish:</b>\n",
        "reg_required": "Ro'yxatdan o'tish majburiy.",
        "choose_lang_menu": "Выберите язык из меню.\nMenyudan tilni tanlang.",
        "send_receipt_prompt": "📷 Chek rasmini yuboring. Chek katta bo'lsa — bir nechta rasm yuboring, keyin Tayyor bosing.",
        "send_qr_prompt": "📷 Chekdagi QR-kod rasmini yuboring yoki havolani nusxalab yuboring (https://new-ofd.soliq.uz/... bilan boshlanadi):",
        "photo_accepted": "✅ {n}-rasm qabul qilindi. Yana yuboring yoki Tayyor bosing.",
        "reading_receipt_multi": "⏳ Chekni o'qiyapman ({n} ta rasm), kuting...",
        "done_btn": "Tayyor",
        "ai_date_not_found": "📅 Sana: <b>topilmadi</b>",
        "ai_no_items": "⚠️ Mahsulotlar topilmadi",
        "final_check_header": "<b>Chek ma'lumotlarini tekshiring:</b>\n",
        "final_shop": "Sex: {val}",
        "final_payment": "To'lov: {val}",
        "final_supplier": "Yetkazib beruvchi: {val}\n",
        "final_items_header": "<b>Mahsulotlar ({val} ta):</b>",
        "final_item_line": "{i}. {nom} — {qty} dona x {price} = {total}",
        "final_receipt_tmc_note": "\n<b>TMC:</b> {tmc}\n<b>Izoh:</b> {note}",
        "final_total": "\n<b>JAMI:</b> {val}",
        "final_ask": "\nBarchasi to'g'rimi?",
        "qr_not_found": "❌ Rasmlarda soliq.uz havolasi bilan QR-kod topilmadi. Iltimos, chekdan QR-kodning alohida rasmini yuboring.",
        "qr_found": "✅ Chek havolasi topildi: {link}",
        "edit_menu_title": "Nimani o'zgartirmoqchisiz, tanlang:",
        "edit_supplier_btn": "🏢 Yetkazib beruvchi",
        "edit_item_btn": "🛍 {nom}",
        "edit_done_btn": "✅ Tayyor",
        "edit_full_manual_btn": "✏️ To'liq qo'lda kiritish",
        "edit_item_title": "«{nom}» mahsulotida nimani o'zgartirasiz?",
        "edit_name_btn": "🏷 Nomi",
        "edit_price_btn": "💰 Narxi",
        "edit_qty_btn": "📦 Miqdori",
        "edit_back_btn": "🔙 Ortga",
        "enter_new_supplier": "Yangi yetkazib beruvchini kiriting:",
        "enter_new_name": "Yangi nomni kiriting:",
        "enter_new_price": "Yangi narxni kiriting:",
        "enter_new_qty": "Yangi miqdorni kiriting:",
        "edit_saved": "✅ O'zgarishlar muvaffaqiyatli saqlandi!",
        "edit_grand_total_btn": "💰 Jami summa",
        "enter_new_grand_total": "Yangi jami summani kiriting:"
    }
}
